# Generated by Django 2.2.1 on 2019-05-06 08:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('term_db', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='measureddata',
            options={'verbose_name': 'Measured Data', 'verbose_name_plural': 'Measured Data'},
        ),
    ]
